# Generated by Django 4.2.3 on 2023-08-16 11:08

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='proof_of_pay',
            field=cloudinary.models.CloudinaryField(default='https://moonvillageassociation.org/wp-content/uploads/2018/06/default-profile-picture1-768x768.jpg', max_length=255, verbose_name='image'),
        ),
    ]
